version: "3.8"

services:
  api:
    build: .
    container_name: mypelvic_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
